### ISSUE TITLE
No doc about adding the new field to the lists that will sort by it

### ISSUE THREAD

**Issue by gjsjohnmurray** [znuny/Znuny4OTRS-SortByLastContact#10]
I suggest you add info to the PDF telling users how they can (if they want to) add the new DynamicField_TicketLastCustomerContactTime field as a column on the lists that will now initially sort by this value.

For example, in SysConfig add a row to the    Ticket::Frontend::AgentTicketLockedView###DefaultColumns item, with Key=DynamicField_TicketLastCustomerContactTime and Content=1. Then individual users can customize their Locked Tickets list, adding the extra column at the position they desire.

**Comment by thorsteneckel** [comment]
Hi @gjsjohnmurray , thanks for your proposal! We definitely will add this to the documentation. @dennybresch could you please take a look in your spare time?

**Comment by dennybresch** [comment]
Hi @gjsjohnmurray,

we improved our documentation a bit.
Actually this is a default configuration which is independent of this packet. But you're right, indeed it is nice to know.

Here you can see the addition:
https://github.com/znuny/Znuny4OTRS-SortByLastContact/commit/49b6ea28711bd0ad55ee22f5eccffbbbf2156c6a

It is helpful enough?

Best regards and thank you for your report.

**Comment by gjsjohnmurray** [comment]
That's excellent. Thank you for adding the information.
