### ISSUE TITLE
Anzeigen in Medium / Large Ansicht

### ISSUE THREAD

**Issue by deniiz** [znuny/Znuny4OTRS-SortByLastContact#13]
Moin die Herren,
wie kriege ich es hin das ich unter der Medium und Large Ansicht die Spalte mit Ticketlastcustomercontacttime angezeigt bekomme.
Dank im Voraus

**Comment by hanneshal** [comment]
Hi,

schau mal hier (für OTRS 5):
https://github.com/OTRS/otrs/blob/rel-5_0/Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewMedium.tt#L128

Dort steht wie man Dynamische Felder eingebunden werden können. Diese Änderung ist allerdings statisch für alle User, da die Spalten Logik der S Ansicht dort nicht unterstützt wird.
Das Feld mit dem Datum heißt: TicketLastCustomerContactTime

Bitte pack die angepasste Datei, mit entsprechenden Code Markern, dann in ein eigenes Theme oder in den Custom Ordner unter: 

```
Custom/Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewMedium.tt
```

Gruß
Johannes

**Comment by thorsteneckel** [comment]
I'll close this one here. Feel free to leave feedback if we can help you any further.
