### ISSUE TITLE
Ergänzungen im Language File

### ISSUE THREAD

**Issue by BSG2000** [znuny/Znuny4OTRS-SortByLastContact#6]
Hallo Kollegen,
ich möchte vorschlagen das Language File um folgende Übersetzung zu ergänzen:
`$Self->{Translation}->{'TicketLastCustomerContactTime'} = 'Letzter Kundenkontakt';`
`$Self->{Translation}->{'TicketLastCustomerContactDirection'} = 'Letzter Kontakt durch';`

--> /opt/otrs/Kernel/Language/de_Znuny4OTRSSortByLastContact

**Comment by dennybresch** [comment]
Hallo BSG2000,

Wir haben die Übersetzung der dynamischen Felder in der Version 3.2.1 übernommen.

vielen Dank

viele Grüße,
DennyBresch
