### ISSUE TITLE
Language File - Endung pm fehlt

### ISSUE THREAD

**Issue by BSG2000** [znuny/Znuny4OTRS-SortByLastContact#7]
Im aktuellen Release scheint die Endung `pm` bei dem File `/opt/otrs/Kernel/Language/de_Znuny4OTRSSortByLastContact.pm` zu fehlen. Die Übersetzungen werden dadurch nicht geladen.

**Comment by dennybresch** [comment]
Hallo BSG2000,

herzlichen Dank für diesen Hinweis.
Ist in der Version 3.2.1 gefixed.

viele Grüße,
DennyBresch
