### ISSUE TITLE
Use Znuny4OTRS-Repo helper instead of packagesetup

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-SortByLastContact#9]
Currently the file 'var/packagesetup/Znuny4OTRSSortByLastContact.pm' is used to create the dynamic fields. This is should always be done via the Znuny4OTRS-Repo Helper in a SOPM CodeInstall block, if no special handling is needed.

While switching to the SOPM block another block 'CodeUninstall' should be added to remove the dynamic fields and their content on uninstall.

This issue was created due the discussion of https://github.com/znuny/Znuny4OTRS-SortByLastContact/issues/8

**Comment by dennybresch** [comment]
@hypericum please QA this commit:
https://github.com/znuny/Znuny4OTRS-SortByLastContact/commit/571ec87dfca6640e76a5e3bcf31a5c1568f57014

**Comment by dennybresch** [comment]
@hypericum @thorsteneckel 
Hi guys, this issues is actually finished.

Could you take a look, please?

Thanks you 😄

**Comment by thorsteneckel** [comment]
I gave my thumb up to it: https://github.com/znuny/Znuny4OTRS-SortByLastContact/commit/571ec87dfca6640e76a5e3bcf31a5c1568f57014#commitcomment-17680878

**Comment by hypericum** [comment]
fine 4 me too

**Comment by dennybresch** [comment]
++ Thank you
